FROM python:3.9

RUN apt-get update && apt-get install -y mariadb-client redis-tools redis-server

WORKDIR /usr/src/app

# Copy the requirements file and install dependencies
COPY /src/redis_init_scripts/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy your Python script and entrypoint scripts
COPY /src/redis_init_scripts/fetch_and_populate.py ./
COPY /src/redis_init_scripts/entrypoint.sh ./


# Make entrypoint script executable
RUN chmod +x ./entrypoint.sh

# Set the entrypoint script to be executed
ENTRYPOINT ["./entrypoint.sh"]
