FROM python:3.9

RUN apt-get update && apt-get install -y mariadb-client

WORKDIR /usr/src/app

# Copy the requirements file and install dependencies
COPY /src/mariadb_init_scripts/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy your Python script and entrypoint scripts
COPY /src/mariadb_init_scripts/load_data.py ./
COPY /src/mariadb_init_scripts/entrypoint.sh ./
COPY ../../model_data/predicted_labels.json ./

# Make entrypoint script executable
RUN chmod +x ./entrypoint.sh

# Set the entrypoint script to be executed
ENTRYPOINT ["./entrypoint.sh"]
