version: "3.8"

services:
  db:
    image: mariadb:latest
    restart: always
    env_file:
      - /.env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ./mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
  python-app:
    build:
      context: .
      dockerfile: /src/mariadb_init_scripts/dockerfile_load_data
    depends_on:
      - db
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}

  # redis:
  #   build:
  #     context: .
  #     dockerfile: dockerfile-redis
  #   ports:
  #     - "6379:6379"
  #   depends_on:
  #     - db

  web:
    build:
      context: .
      dockerfile: dockerfile-model
    ports:
      - "8000:8000"
    volumes:
      - ./src/container:/app
      - ./model_binary:/app/model
      - ./src/sdk:/app/sdk
    depends_on:
      - db
      - redis
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}