version: "3.8"

services:
  db:
    image: mariadb:latest
    restart: always
    env_file:
      - /.env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ./mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  load_data_in_mariadb:
    build:
      context: .
      dockerfile: /src/mariadb_init_scripts/dockerfile-load-data-mariadb
    depends_on:
      - db
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ./shared_data:/var/shared

  redis:
    image: redis:latest
    restart: always
    env_file:
      - /.env
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis_data:/data

  load_data_in_redis:
    build:
      context: .
      dockerfile: /src/redis_init_scripts/dockerfile-load-data-redis
    depends_on:
      - db
      - redis
      - load_data_in_mariadb
    env_file:
      - /.env
    volumes:
      - ./shared_data:/var/shared
  web:
    build:
      context: .
      dockerfile: dockerfile-model
    ports:
      - "8000:8000"
    volumes:
      - ./src/container:/app
      - ./model_binary:/app/model
      - ./src/sdk:/app/sdk
    depends_on:
      - db
      - redis
    env_file:
      - /.env
