version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    restart: always
    env_file:
      - /.env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    # volumes:
    #   - mariadb_data:/var/lib/mysql
    volumes:
      - ./mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  data-importer:
    build:
      context: .
      dockerfile: dockerfile-load-data
    depends_on:
      - mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ./data:/data

  redis:
    image: redis:latest
    restart: always
    env_file:
      - /.env
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis_data:/data

  web:
    build:
      context: .
      dockerfile: dockerfile-model
    ports:
      - "8000:8000"
    volumes:
      - ./service:/app
      - ./tiny_model:/app/model
      - ./sdk:/app/sdk
    depends_on:
      - db
      - redis
    env_file:
      - /.env
