version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    restart: always
    env_file:
      - ./.env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ./database/mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  data-importer:
    build:
      context: .
      dockerfile: dockerfile-load-data
    depends_on:
      - mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ./database/data:/data

  redis:
    image: redis:latest
    restart: always
    env_file:
      - .env
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./database/redis_data:/data

  web:
    build:
      context: .
      dockerfile: dockerfile-model
    ports:
      - "8000:8000"
    volumes:
      - ./service:/app/service
      - ./assets:/app/assets
      - ./model_binary:/app/model_binary
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
