FROM python:3.8


WORKDIR /app


COPY ./service/service_requirements.txt /app/service_requirements.txt

RUN pip install --upgrade pip

RUN pip install -r service_requirements.txt

RUN apt-get update && \
    apt-get install -y default-mysql-client && \
    rm -rf /var/lib/apt/lists/*


COPY ./service/main.py /app/service/main.py
COPY ./service/service_config.py /app/service/service_config.py
COPY ./service/service_utils.py /app/service/service_utils.py

COPY ./tiny_model/encoder.pkl /app/tiny_model/encoder.pkl
COPY ./tiny_model/model.onnx /app/tiny_model/model.onnx
COPY ./tiny_model/tokenizer /app/tiny_model/tokenizer

ENV PYTHONPATH="${PYTHONPATH}:/app/service"

COPY ./service/start.sh /app/start.sh

RUN sed -i 's/\r$//' /app/start.sh

RUN chmod +x /app/start.sh

# CMD ["tail", "-f", "/dev/null"]

ENTRYPOINT ["/app/start.sh"]